### ISSUE TITLE
Send private message to the promoted ninja

### ISSUE THREAD

**Issue by RuiL1904** [coderdojobraga/gongo#15]
Feature needed: when a ninja is promoted he receives a private message with the requirements for the next belt.

**Comment by danielsp45** [comment]
I can work on that 👍🏻

**Comment by RuiL1904** [comment]
@danielsp45 I think we could have a JSON file with all the data (requirements, in this case) about the belts. What are your thoughts on it?

**Comment by danielsp45** [comment]
> @danielsp45 I think we could have a JSON file with all the data (requirements, in this case) about the belts. What are your thoughts on it?

Yes I thought of that. I think it is a good idea.

**Comment by RuiL1904** [comment]
Solved by #17.
